language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

stages:
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: tests
      name: "Code Style Check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e flake8
    - stage: tests
      name: "Unit Tests"
      python: 3.6
      before_script:
        - sudo apt-get update
        - sudo apt-get install libcurl4-openssl-dev
        - pip install tox-travis
      script: tox
    - stage: tests
      name: "Documentation Tests"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e docs
    - stage: tests
      name: "Python Code Security Tests"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e bandit

notifications:
  email: false
