language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

stages:
  - name: tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: tests
      name: "Code Style Check"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e flake8
    - stage: tests
      name: "Unit Tests Python 3.6"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e py36
    - stage: tests
      name: "Unit Tests Python 3.7"
      python: 3.7
      before_script:
        - pip install tox-travis
      script: tox -e py37
    - stage: tests
      name: "Documentation Tests"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e docs
    - stage: tests
      name: "Python Code Security Tests"
      python: 3.6
      before_script:
        - pip install tox-travis
      script: tox -e bandit

notifications:
  email: false
