language: python

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36

install: pip install tox

stages:
  - name: unit tests
    if: type IN (push, pull_request)

jobs:
  include:
    - stage: unit tests
      python: 3.6
      before_script:
        - pip install tox-travis
      # command to run tests
      script: tox

notifications:
  email: false
